### ISSUE TITLE
Local server using gpt4all has a broken link; LLM responses come back as gibberish

### ISSUE THREAD

**Issue by eliburke** [psychic-api/rag-stack#3]
Out of the box on an M2 Mac running Ventura
```
> git clone
> ./run-dev.sh
```
ragstack-ui comes up, but the send button posts to the wrong URL _http://localhost:5173/undefined/ask-question_ and dies with an exception. 

I edited ragstack-ui/src/utils.tsx and hard coded the post URL to _http://localhost:8080/ask-question_

Clicking "Send" with an empty text field, or a prompt, or attaching a PDF, generates a gibberish response. 
Server log shows e.g.
```
INFO:     Application startup complete.
[]
DDDH<8<8888H,D<8<,8,D8H,,HH8<8<<H,H,HDH,8D<H8H<HD8HH88,<,88<H,DH8DD,,,<,H8DD88D,8H,8DH<H,H88H8,8<D<,88D,D<<888D,HH,HDHHD8<D,8<<D<,8,DHH8,D,DD<<D,D,HD8,D8H<HHD<<H,<<<H8<,,,,8H8H88H8H<DHDH8<<,8H,H,H8DH8D8H<D,,D,<,H,8,D,<<8DHHDD,H<8HDD888<D,HHHDDH8<8HD,H<D<,<INFO:     127.0.0.1:58636 - "POST /ask-question HTTP/1.1" 200 OK
```

Is this supported on Mac? Is there something else I need to do for it to function?

**Comment by Ayan-Bandyopadhyay** [comment]
It's possible that the gpt4all model is corrupted based on the discussion [here](https://github.com/langchain-ai/langchain/issues/4837). Could you try deleting the `ggml-gpt4all-j-v1.3-groovy.bin` file in `server/llm/local/` and re-running the script?

And as for the post url, there was a missing step that I'll add to the instructions. You'll need to copy the contents of `ragstack-ui/local.env` into `ragstack-ui/.env`

**Comment by eliburke** [comment]
Thanks @Ayan-Bandyopadhyay. The env fixed the UI, and re-downloading the model fixed the gibberish. Appreciate the quick response!
